### ISSUE TITLE
`_config.yml` is Invalid

### ISSUE THREAD

**Issue by nicktabick** [amykotas/startjekyll#1]
Your `_config.yml` is using curly quotes for some of the values when it should be using straight quotes throughout the entire file.

[Line 21](https://github.com/amykotas/startjekyll/blob/gh-pages/_config.yml#L21): `url: “https://amykotas.github.io”` should be `url: "http://amykotas.github.io"`
[Line 32](https://github.com/amykotas/startjekyll/blob/gh-pages/_config.yml#L32): `include: ['_pages']` should be `include: ['_pages']`

Fixing the misspelled `Gemfile` in your `exclude` section couldn't hurt, either. ;)

**Comment by amykotas** [comment]
Resolved. 🎉
